### PR TITLE
Adding Team Porygon to the scrapper.

### PR DESCRIPTION
**Pull request by oilimedev**
Added Team Porygon scrapper file.

### CODE REVIEW

**Comment by oilimedev** [comment]
Will wait for the showcase to be updated with the correct format.

**Comment by LemonMantis5571** [comment]
Hi, I saw your team is formatting the showcase already, but giving my grain of sand you could do it this way.

```
$currentUser = null;
// Track usernames and their Pokémon counts
foreach ($dom->getElementsByTagName('*') as $node) {
    // Check for username span
    if ($node->nodeName == 'span' && $node->getAttribute('style') == 'font-size:16px;') {
        if (preg_match('/>([a-zA-Z]+)</', $dom->saveHTML($node), $usernameMatches)) {
            $currentUser = trim($usernameMatches[1]);
            $users[$currentUser] = [
                'imageCount' => 0,
                'pokemons' => []
            ];
        }
    }

    // Check for Pokémon images
    if ($currentUser && $node->nodeName == 'img') {
        $src = $node->getAttribute('src');
        if (strpos($src, 'pokemondb.net') !== false) {
            $users[$currentUser]['pokemons'][] = $src;
            $users[$currentUser]['imageCount']++;
        }
    }
}

```

image

**Comment by Gamer2020** [comment]
Hi. So  the issue with this is that many showcases use images to show egg,alpha, safari, etc. These images end up getting counted without a lot of customization.

This will work only as long as they don't put an image that doesn't use the url.

**Comment by oilimedev** [comment]
Exactly as Gamer said, that's why I ruled out trying to count the images.
I've been trying multiple options with our showcase keeper, like an invisible count after the name, or putting the list inside a Spoiler tag in a second comment too. Will push changes after we rule out an option, or abandon if it's too much hazzle for our showcase keeper.

**Comment by LemonMantis5571** [comment]
Yeah, I think you can still use it to count the shinies faster and avoid having your showcase keeper count them one by one (if you haven't already lmao) then format the post with the amount of each member. There are like over 1,000 shinies.

**Comment by Gamer2020** [comment]
At the end of the day, do what works best for your team.

If no other option I can implement with reading the images. If they all use the same url it shouldn't be too bad. Other showcases tend to have images from different sources but it may work for your team. If anything breaks down the road we can always revist and adjust accordingly.

**Pull request merged**
